name = "lacuna-api"
main = "src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "lacuna-db"
database_id = "aa2e68ac-6b77-4c8f-9947-6865d5e8d330"

[vars]
FRONTEND_ORIGIN = "https://lacuna-app.pages.dev"
RP_ID           = "lacuna-app.pages.dev"
